version: '3.8'
services:
  server:
    build:
      context: .
      args:
        - REACT_APP_FIREBASE_API_KEY=${REACT_APP_FIREBASE_API_KEY}
        - REACT_APP_FIREBASE_PROJECT_ID=${REACT_APP_FIREBASE_PROJECT_ID}
        - REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${REACT_APP_FIREBASE_MESSAGING_SENDER_ID}
        - REACT_APP_FIREBASE_APP_ID=${REACT_APP_FIREBASE_APP_ID}
        - REACT_APP_FIREBASE_MEASUREMENT_ID=${REACT_APP_FIREBASE_MEASUREMENT_ID}
    image: local-pootcuppeelek-server
    ports:
      - "3001:8080"
environment:
  - PORT=${PORT}
  - NODE_ENV=${NODE_ENV}
  - GOOGLE_APPLICATION_CREDENTIALS=/app/pootcuppeelek-316a576ed35c.json
  - CORS_ORIGIN=${CORS_ORIGIN}
  - LOG_LEVEL=${LOG_LEVEL}
  - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
  - FIREBASE_PRIVATE_KEY_BASE64=${FIREBASE_PRIVATE_KEY_BASE64}
  - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
  - REACT_APP_FIREBASE_API_KEY=${REACT_APP_FIREBASE_API_KEY}
  - REACT_APP_FIREBASE_PROJECT_ID=${REACT_APP_FIREBASE_PROJECT_ID}
  - REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${REACT_APP_FIREBASE_MESSAGING_SENDER_ID}
  - REACT_APP_FIREBASE_APP_ID=${REACT_APP_FIREBASE_APP_ID}
  - REACT_APP_FIREBASE_MEASUREMENT_ID=${REACT_APP_FIREBASE_MEASUREMENT_ID}
  - REACT_APP_API_URL=${REACT_APP_API_URL}
volumes:
      - ./pootcuppeelek-316a576ed35c.json:/app/pootcuppeelek-316a576ed35c.json